Add README and other help text related to the commands
OnePunMan/thedasbot pull request #11
Opened 2020-05-08 18:03 UTC by OnePunMan

2020-05-08 18:15 UTC, Cypheruim commented on README.md
> +The DAS bot is a webhook based telegram bot written in Python 3.7 deployed on AWS Lambda. It is capable of fetching jokes, fun facts, as well as as multiple choice trivia questions and fetch insights
"as" duplicated

2020-05-08 18:15 UTC, Cypheruim commented on README.md
> +Gets insights from Google Trends; capble graphing trends, pulling top trends, and realtime trending searches. It uses the [pytrends](https://github.com/GeneralMills/pytrends) library.
use "real-time"

2020-05-08 18:15 UTC, patelmohit approved these changes
LGTM 👍

2020-05-08 18:40 UTC, patelmohit commented on README.md
> +* `/trivia any hard` - Hard question from a random category
Can you include pictures of the bot from Telegram here? It would be nice to see the UI here on Github,

2020-05-09 02:09 UTC, george-lim requested changes
I have many suggestions to improve grammar and follow README practices.

2020-05-09 02:09 UTC, george-lim commented on README.md
> +The DAS bot is a webhook based telegram bot written in Python 3.7 deployed on AWS Lambda. It is capable of fetching jokes, fun facts, as well as as multiple choice trivia questions and fetch insights
```suggestion
The DAS bot is a webhook-based Telegram bot that is written in Python 3.7 and deployed on AWS Lambda. It is capable of telling jokes, sharing fun facts, hosting trivia sessions, and fetching insights from Google Trends.
```

2020-05-09 02:09 UTC, george-lim commented on README.md
> +- `/trivia help` brings up the list of available categories and difficulties. Categories do not need to exactly match what's listed, as long it's enough to uniquely identify it. Leaving any arguments
```suggestion
- `/trivia help` brings up the list of available categories and difficulties. Categories support fuzzy matching. All arguments default to `any`, which selects a random category/difficulty.
```

2020-05-09 02:09 UTC, george-lim commented on README.md
> +* `/trivia any hard` - Hard question from a random category
I personally wouldn't add UI screenshots, it's not really the norm unless you actually have custom UI (which you don't, you're using Telegram)

2020-05-09 02:09 UTC, george-lim commented on README.md
> +Gets insights from Google Trends; capble graphing trends, pulling top trends, and realtime trending searches. It uses the [pytrends](https://github.com/GeneralMills/pytrends) library.
```suggestion
Fetches insights from Google Trends. Features the ability to graph trends by keyword and list top / trending keywords by year. All communication is handled using the [pytrends](https://github.com/GeneralMills/pytrends) library.
```

2020-05-09 02:09 UTC, george-lim commented on README.md
> +Got an feature idea? Make a pull request! New features and improvements are always welcome! New commands should inherit the `BotCommand` class, override at least the `execute` method, and placed insi
```suggestion
New features and improvements are always welcome! New commands should inherit the `BotCommand` class, override the `execute` method, and be placed inside the `commands/` directory. Also, the command must be added to the `AVAILABLE_COMMANDS` constant in `command_parser.py` to be recognized by the parser.
```

2020-05-09 02:09 UTC, george-lim commented on README.md
> +My local webhook setup uses [bottle](https://pypi.org/project/bottle/) and [ngrok](https://ngrok.com/download). This [guide](https://hackernoon.com/serverless-telegram-bot-on-aws-lambda-851204d4236c)
```suggestion
To test the project locally:
1. Setup [bottle](https://pypi.org/project/bottle/) and [ngrok](https://ngrok.com/download)
2. Setup the local environment using the following [guide](https://hackernoon.com/serverless-telegram-bot-on-aws-lambda-851204d4236c)
3. Launch `ngrok` and update the webhook to the project
4. Run `install_local`, then `python3 local.py`
```

2020-05-10 01:22 UTC, george-lim approved these changes

2020-05-10 01:27 UTC, OnePunMan commented
Thanks for the reviews folks! @george-lim thanks for taking the time to suggest changes!

2020-05-10 01:28 UTC, merged