Architecture refactor #2 (Bot v3)
OnePunMan/thedasbot pull request #6
Opened 2020-04-15 16:37 UTC by OnePunMan

- Relocating response logic to `BotCommand` to increase customizability
- Cleaning up imports
- Tweaking UT's to reflect new changes

2020-04-15 17:07 UTC, george-lim requested changes
Good start, have a couple things that I would do differently to make the code cleaner. I think you should solve the import problem in another PR, because there is a lot of duplicate imports (like for each command for example). I think you should use `logging` instead of print though.

2020-04-15 17:07 UTC, george-lim commented on commands/botcommand.py
> +        if self.query.is_edited and not ALLOW_EDITED_MESSAGES:
Are you ever planning on allowing edited messages? If not, you should just remove this flag and if statement altogether. It's a bad idea to have flags that will NEVER change.

2020-04-15 17:07 UTC, george-lim commented on commands/botcommand.py
>          super().__init__()
I personally would remove `super().__init__()` because it's just an object. This makes me think that your BotCommand is a subclass of a custom object. I would also remove the explicit subclass object here as well for the same reason

2020-04-15 17:07 UTC, george-lim commented on commands/botcommand.py
> +            print("Response is None: nothing sent back")
I think you should consider using `logging` library instead of `print` everywhere. You can do stuff like `logging.warning("...")` to be more explicit.

2020-04-15 17:07 UTC, george-lim commented on commands/botcommand.py
> +        data = dict()
Avoid using very simple non-descriptive variables like `data` please. I would prefer something like `send_message_json`.

2020-04-15 17:07 UTC, george-lim commented on commands/botcommand.py
> +            data.update(self.other_params)
I'm not a fan of having `other_params`. I would split this function into 2 functions:  `format_send_message_json` and `send_message`. Then, have subclass commands override `format_send_message_json` to add their own parameters (instead of storing `other_params` in the parent class, it shouldn't know anything about "extra" parameters).

A child class could do then do something like:

```
def handle_normal_query(self, response):
  send_message_json = super.format_send_message_json(...)
  # do stuff with new parameters
  super.send_message(send_message_json)
```

2020-04-15 18:19 UTC, OnePunMan commented on commands/botcommand.py
> +            print("Response is None: nothing sent back")
Good suggestion, I'll keep a note of this for future changes

2020-04-15 23:17 UTC, george-lim commented on commands/botcommand.py
> +            print("Response is None: nothing sent back")
Sure, this can be done in another PR

2020-04-18 02:26 UTC, george-lim approved these changes
LGTM 👍

2020-04-18 02:30 UTC, merged